# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10

workflows:
  version: 2.1
  deploy-heroku:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only: 
                - master